services:
  celtics-app:
    build: .
    container_name: celtics-app
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
      - OracleConnection=User Id=system;Password=oracle;Data Source=db/XE
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: gvenzl/oracle-xe:21-slim
    container_name: db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
    volumes:
      - oracle_data:/opt/oracle/oradata
    restart: unless-stopped
    shm_size: 1g

volumes:
  oracle_data:
    name: celtics_oracle_volume